### ISSUE TITLE
Unable to parse hostname https://domain.net.za: tld not found

### ISSUE THREAD

**Issue by WilliamStam** [aschzero/hera#3]
seems that if the domain (in my case something like home.net.za) results in the above error. 

````
hera               | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
hera               | [s6-init] ensuring user provided files have correct perms...exited 0.
hera               | [fix-attrs.d] applying ownership & permissions fixes...
hera               | [fix-attrs.d] 01-log-permissions: applying...
hera               | [fix-attrs.d] 01-log-permissions: exited 0.
hera               | [fix-attrs.d] done.
hera               | [cont-init.d] executing container initialization scripts...
hera               | [cont-init.d] 01-setup-logs: executing...
hera               | [cont-init.d] 01-setup-logs: exited 0.
hera               | [cont-init.d] 02-symlink-certs: executing...
hera               | [cont-init.d] 02-symlink-certs: exited 0.
hera               | [cont-init.d] done.
hera               | [services.d] starting services
hera               | [INFO] Hera v0.2.4 has started
hera               | [INFO] Found certificate: domain.net.za.pem
hera               | [services.d] done.
hera               | [INFO] Hera container found, connecting to e6d474a.......
hera               | [ERROR] Unable to parse hostname https://pihole.domain.net.za: tld not found
hera               | [INFO] Hera is listening

````

my docker compose: (${DOMAIN} is basicaly just my domain as in domain.net.za)
```
pihole:
      container_name: pihole
      image: pihole/pihole
      ports:
         - 53:53
         - 53:53/udp
         - 67:67/udp
         - 8081:80
      environment:
         TZ: ${TZ}
         WEBPASSWORD: stars
         ServerIP: 192.168.0.10
         PROXY_LOCATION: pihole
         VIRTUAL_HOST: pihole.${DOMAIN}
         VIRTUAL_PORT: 80
      volumes:
         - /storage.config/pihole:/etc/pihole/
         - /storage.config/dnsmasq:/etc/dnsmasq.d/
         - /storage.config/05-lan.conf:/etc/dnsmasq.d/05-lan.conf
      dns:
         - 127.0.0.1
         - 1.1.1.1
         - 8.8.8.8
      cap_add:
         - NET_ADMIN
      restart: unless-stopped
      labels:
         - hera.hostname=pihole.${DOMAIN}
         - hera.port=80

   hera:
      image: aschzero/hera
      container_name: hera
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /storage.config/hera/certs:/certs
         - /storage.config/hera/logs:/var/log/hera
````

also +1 to the idea of being able to configure it directly. like set up hostdomain in the block and then use labels for subdomains or folders?
